#!/usr/bin/env python

def localise(lang, string, db):
    return db[lang].get(string, string)

strings = {"cy": {"Numerical Analysis": "Dadansoddi Rhifiadol", 
                  "LabVIEW Tutorial": "Tiwtorial LabVIEW",
                  "Density of States": "Dwysedd Cyflyrau",
                  "Chaotic Double Pendulum": "Pendil Dwbl Caotig",
                  "Electron Spin Resonance": "Cyseiniant Sbin Electronau",
                  '<font face="AvenirNext">α</font>, <font face="AvenirNext">β</font>, and <font face="AvenirNext">γ</font>-radiation': 'Ymbelydredd <font face="AvenirNext">α</font>, <font face="AvenirNext">β</font> a <font face="AvenirNext">γ</font>',
                  "Franck Hertz": "Franck Hertz",
                  "Rutherford Scattering": "Gwasgariad Rutherford",
                  "Hubble's Law": "Deddf Hubble",
                  "Balmer Series of the Hydrogen Atom": "Cyfres Balmer yr Atom Hydrogen",
                  "Measurement of Viscosity": "Mesur Gludedd",
                  "Polarimeter": "Polarimedr",
                  "Multiple Slit Diffraction": "Diffreithiant Holltau Lluosog",
                  "Edser Butler Method": "Dull Edser-Butler",
                  "B/H Curve": "Cromlin B/H",
                  "Spectroscopic Analysis": "Dadansoddiad Spectrosgopig",
                  "LabVIEW: Calibrating a Thermistor": "LabVIEW: Graddnodi Thermistor",
                  "Diffraction at a Straight Edge": "Diffreithiant gan ymyl syth",
                  "Gyroscope": "Gyrosgop",
                  "More Spectroscopic Analysis": "Rhogor o ddadansoddiad spectrosgopig",
                  "Group Project – Week 1": "Prosiect Grŵp – Wythnos 1",
                  "Group Project – Week 2": "Prosiect Grŵp – Wythnos 2",
                  "Group Project – Week 3": "Prosiect Grŵp – Wythnos 3",
                  "Group Project – Week 4": "Prosiect Grŵp – Wythnos 4",
                  "Group Project – Presentations /100": "Prosiect Grŵp – Cyflwyniadau /100",
                  "Report write-up time": "Amser i ysgrifennu adroddiad",
                  '<font face="FuturaHeavy">4pm</font>: Submission of report and lab diary': '<font face="FuturaHeavy">4yp</font>: Cyflwyno adroddiad a dyddiadur',
                  'Submission of lab diary': 'Cyflwyno dyddiadur',
                  "* Do not write up these experiments": "* Peidiwch ag ysgrifennu am yr arbrofion hyn",
                  "Department of Physics • Lab Diary": "Adran Ffiseg • Dyddiadur Labordy",
                  "Level {} • {}–{} TB{}": "Lefel {} • {}–{} BD{}",
                  "Pair": "Pâr",
                  'Mark /10': 'Marc /10',
                  'Marker': 'Marcwr',
                  'Date': 'Dyddiad',
                  'Number': 'Rhif',
                  'Code': 'Cod',
                  'Page': 'Tudalen',
                  'Title': 'Teitl',
                  'Cohort': 'Carfan'},
           "en": {}}

